sonar.projectKey=jojma-entreprise
sonar.projectName=JOJMA_ENTREPRISE
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_4a7aea83a2753bf54f128ca57696a824ac7cb2bd

sonar.sourceEncoding=UTF-8
sonar.sources=backend,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.git/**,**/*.min.js,python/**

sonar.javascript.node.maxspace=4096