-- Initial migration: create demandes and demande_logs
-- Generated by assistant on 2026-04-08

CREATE TABLE IF NOT EXISTS `demandes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `type_demande` VARCHAR(50) NOT NULL,
  `source_formulaire` VARCHAR(100) NULL,
  `nom` VARCHAR(100) NULL,
  `prenom` VARCHAR(100) NULL,
  `email` VARCHAR(150) NULL,
  `telephone` VARCHAR(50) NULL,
  `adresse` VARCHAR(255) NULL,
  `entreprise` VARCHAR(150) NULL,
  `domaine_activite` VARCHAR(150) NULL,
  `sujet` VARCHAR(255) NULL,
  `message` TEXT NULL,
  `statut` ENUM('nouveau','lu','en_cours','en_attente','traite','archive','rejete') NOT NULL DEFAULT 'nouveau',
  `priorite` ENUM('basse','normale','haute','urgente') NOT NULL DEFAULT 'normale',
  `est_lu` TINYINT(1) NOT NULL DEFAULT 0,
  `assigne_a` BIGINT UNSIGNED NULL,
  `admin_notes` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `archived_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `idx_statut` (`statut`),
  INDEX `idx_priorite` (`priorite`),
  INDEX `idx_created_at` (`created_at`),
  INDEX `idx_est_lu` (`est_lu`),
  INDEX `idx_assigne_a` (`assigne_a`),
  INDEX `idx_email` (`email`),
  FULLTEXT KEY `ft_sujet_message` (`sujet`, `message`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `demande_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `demande_id` BIGINT UNSIGNED NOT NULL,
  `admin_id` BIGINT UNSIGNED NULL,
  `action_type` VARCHAR(50) NOT NULL,
  `description` TEXT NULL,
  `meta` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_demande_logs_demande` FOREIGN KEY (`demande_id`) REFERENCES `demandes`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
