import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'A Propos',
    'nav.services': 'Services',
    'nav.converter': 'Convertisseur',
    'nav.packs': 'Packs AR',
    'nav.ar': 'Réalité Augmentée',
    'nav.ar_home': 'AR Accueil',
    'nav.ar_experiences': 'Expériences AR',
    'nav.contact': 'Contact',
    'auth.login': 'Se connecter',
    'auth.register': "S'inscrire",
    'auth.logout': 'Déconnexion',
    'auth.welcome_back': 'Bon retour !',
    'auth.login_desc': 'Connectez-vous pour accéder à votre espace.',
    'auth.create_account': 'Créer un compte',
    'auth.register_desc': 'Commencez votre aventure avec JOJMA gratuitement.',
    'auth.email': 'Email professionnel',
    'auth.password': 'Mot de passe',
    'auth.name': 'Nom complet',
    'auth.remember': 'Se souvenir de moi',
    'auth.forgot': 'Oublié ?',
    'auth.no_account': 'Pas encore de compte ?',
    'auth.have_account': 'Déjà un compte ?',
    'auth.register_free': "S'inscrire gratuitement",
    'auth.terms_agree': "J'accepte les Conditions d'utilisation et la Politique de confidentialité.",
    'home.hero_title': 'Transformez Vos Modèles 3D en Expériences AR Immersives',
    'home.hero_desc': 'JOJMA est la plateforme leader pour convertir, gérer et déployer vos actifs 3D en réalité augmentée. Simple, rapide et professionnel.',
    'home.hero_cta': 'Commencer Gratuitement',
    'home.hero_demo': 'Voir la Démo',
    'home.stats_users': 'Utilisateurs Actifs',
    'home.stats_models': 'Modèles Convertis',
    'home.stats_countries': 'Pays Desservis',
    'about.title': 'À Propos de JOJMA',
    'about.subtitle': 'Innover dans le monde de la Réalité Augmentée',
    'about.mission': 'Notre Mission',
    'about.mission_text': 'Démocratiser l\'accès à la réalité augmentée en fournissant des outils puissants et intuitifs pour les créateurs et les entreprises du monde entier.',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Une question ? Notre équipe est là pour vous aider.',
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'home.domain_tableau': 'Tableau',
    'home.domain_sculpture': 'Sculpture',
    'home.domain_moderne': 'Art Moderne',
    'home.domain_abstraite': 'Art Abstrait',
    'home.stats_title': 'Plateforme AR #1',
    'home.stats_desc': 'Nous sommes experts en réalité augmentée pour tous types d\'objets.',
    'home.services_title': 'Nos Services',
    'home.services_subtitle': 'Découvrez nos différentes offres adaptées à vos besoins en matière de 3D et réalité augmentée.',
    'home.service_free_title': 'Convertisseur 3D Gratuit',
    'home.service_pro_title': 'Modélisation 3D & Réalité Augmentée',
    'home.service_custom_title': 'Solution AR sur Mesure',
    'home.choose_plan': 'Choisir ce Plan',
    'home.recommended': 'Recommandé',
    'home.service_free_features': 'Téléchargement de fichiers 3D : STL, OBJ, FBX, JPG, PNG|Conversion automatique en GLB, GLTF|Optimisation des fichiers pour la Réalité Augmentée|Téléchargement du fichier converti (GLB, GLTF)|Génération d\'une prévisualisation 3D en ligne|Compatible avec Mobile & PC',
    'home.service_pro_features': 'Consultation avec nos experts 3D|Téléchargement des fichiers : images, plans, plans techniques|Création de modèles 3D personnalisés|Conversion en formats compatibles : GLB, GLTF|Génération d\'un Lien AR unique pour chaque produit|Compatible avec Mobile & Tablette|Partage facile du produit en AR|Génération de QR Codes pour modèles|Optimisation des fichiers pour une meilleure performance|Intégration E-commerce (Shopify, WooCommerce...)',
    'home.service_custom_features': 'Téléchargement de Produits 3D GLB|Visualisation en Réalité Augmentée|Génération de Liens AR & QR Code|Compatible Mobile & PC|Intégration avec Shopify, WooCommerce|Personnalisation du Fond & Éclairage|Mode Multi-Produits|Sécurité & Protection Anti-vol',
    'home.domain_title': 'Domaine en Réalité Augmentée',
    'home.platform_title': 'Notre Plateforme de Réalité Augmentée',
    'home.platform_subtitle': 'Nous offrons une plateforme complète pour visualiser, convertir et partager vos modèles 3D en réalité augmentée. Découvrez nos services qui révolutionnent la manière dont vous interagissez avec vos objets.',
    'home.feature_viz_title': 'Visualisation 3D',
    'home.feature_viz_desc': 'Visualisez vos modèles 3D en réalité augmentée directement depuis votre navigateur ou appareil mobile.',
    'home.feature_conv_title': 'Conversion de Modèles',
    'home.feature_conv_desc': 'Convertissez vos modèles entre différents formats (GLTF, OBJ, FBX, STL) avec une qualité exceptionnelle.',
    'home.feature_share_title': 'Partage Facile',
    'home.feature_share_desc': 'Partagez vos modèles AR avec vos clients, collègues ou amis via un simple lien ou code QR.',
    'home.platform_detail_title': 'Plateforme AR complète et puissante',
    'home.platform_detail_features': 'Téléchargez facilement vos fichiers aux formats GLB, GLTF, et USDZ pour les convertir instantanément en modèles AR interactifs|Visualisez vos produits en AR directement dans votre espace personnel et testez l\'expérience utilisateur avant de la partager|Intégrez facilement vos modèles AR sur votre site web ou CMS avec un simple code que vous pouvez copier-coller',
    'home.try_now': 'Essayer maintenant',
    'home.dashboard_badge': 'Tableau de bord facile à utiliser',
    'home.dashboard_title': 'Voyez tout. Contrôlez tout.',
    'dashboard.title': 'Tableau de bord',
    'dashboard.overview': 'Vue d\'ensemble',
    'dashboard.conversions': 'Conversions',
    'dashboard.ar': 'Réalité Augmentée',
    'dashboard.profile': 'Profil',
    'dashboard.settings': 'Paramètres',
    'dashboard.home': 'Accueil',
    'dashboard.logout': 'Déconnexion',
    'admin.title': 'Administration JOJMA',
    'admin.overview': 'Vue d\'ensemble',
    'admin.users': 'Utilisateurs',
    'admin.models': 'Modèles 3D',
    'admin.support': 'Support',
    'admin.logs': 'Logs activité',
    'admin.errors': 'Erreurs système',
    'admin.client_area': 'Espace client',
    'admin.admin': 'Admin',
    'admin.settings': 'Paramètres',
    'home.dashboard_desc1': 'Gardez un œil sur ce qui est important à vos yeux grâce à notre tableau de bord facile à utiliser.',
    'home.dashboard_desc2': 'Conçu pour convenir aussi bien aux débutants qu\'aux professionnels, ce tableau vous permet de voir les performances de votre plateforme, d\'effectuer des conversions et bien plus encore en un instant.',
    'home.dashboard_features': 'Conversion entre 10 formats populaires|Interface simple et intuitive|Processus de conversion rapide',
    'home.explore_features': 'Explorer les fonctionnalités',
    'home.support_title': 'Support francophone disponible 24h/24, 7j/7',
    'home.support_features': 'Discutez par chat en direct ou par email avec notre équipe d\'experts dès que vous en avez besoin|Nos spécialistes parlent couramment français et vous accompagnent dans la création de vos fichiers 3D (GLB, GLTF) personnalisés|Temps d\'attente minimal : notre équipe de support réactif vous répond généralement en moins de 2 minutes|Nous générons pour vous le code d\'intégration prêt à l\'emploi pour votre plateforme ou CMS',
    'home.contact_support': 'Contacter le support',
    'home.online': 'En ligne',
    'home.chat_user_msg': 'Bonjour, je souhaite créer un modèle 3D de mon produit pour mon site e-commerce.',
    'home.chat_support_msg1': 'Bonjour, je serais ravi de vous aider. La procédure est simple et se déroule en trois étapes. Laissez-moi vous montrer comment faire.',
    'home.chat_support_steps': 'Envoyez-nous les photos ou la maquette de votre produit|Nous créerons le fichier GLB/GLTF pour vous|Nous vous fournirons le code d\'intégration pour votre site',
    'home.dashboard_formats_title': 'Formats supportés par notre plateforme',
    'home.dashboard_supported_ext': 'Extensions prises en charge',
    'home.dashboard_used': 'Utilisés:',
    'home.mission_title': 'Chez JOJMA Group, notre mission est de démocratiser la réalité augmentée pour tous. Nous avons développé une plateforme complète permettant de convertir, visualiser et partager des modèles 3D en toute simplicité.',
    'home.mission_desc': 'Notre équipe d\'experts passionnés travaille continuellement à améliorer notre technologie pour offrir la meilleure expérience possible. Que vous soyez un artiste, une entreprise ou un particulier, notre plateforme vous permet de donner vie à vos créations dans le monde réel grâce à la réalité augmentée.',
    'home.founder_role': 'Fondateur & CEO, JOJMA Group',
    'home.read_full_story': 'Lire l\'histoire complète',
    'home.cta_title': 'Transformez vos modèles 3D et visualisez-les en réalité augmentée',
    'home.cta_desc': 'Essayez notre plateforme gratuite de conversion et de visualisation AR avec plus de 10 formats supportés.',
    'home.get_started': 'Commencer',
    'home.final_support_title': 'Support 24/24, Nous sommes toujours disponibles.',
    'home.final_support_desc': 'Contactez-nous à tout moment, nous sommes là pour vous aider.',
    'home.support_phone_label': 'Appelez-nous',
    'home.support_phone_info': '+212 660 339 034',
    'home.support_chat_label': 'Chattez avec nous',
    'home.support_chat_info': 'Chat en direct',
    'home.support_insta_label': 'Suivez-nous sur Instagram',
    'home.support_insta_info': 'Visitez notre page',
    'home.support_faq_label': 'Trouvez des réponses',
    'home.support_faq_info': 'Base de connaissances',
    'home.support_blog_label': 'Découvrez nos articles',
    'home.support_blog_info': 'Blog sur l\'AR',
    'home.faq_title': 'Des Questions ? Nous avons les Réponses.',
    'home.faq_questions': 'Comment fonctionne la Réalité Augmentée ?|Quels appareils sont compatibles ?|Comment intégrer l\'AR à mon site web ?|Puis-je utiliser mes propres modèles 3D ?|L\'AR fonctionne-t-elle sans application mobile ?|Quels formats de fichiers 3D sont pris en charge ?|Comment générer un lien AR partageable ?|Les modèles 3D conservent-ils leurs textures en AR ?',
    'home.see_more': 'Voir plus',
    'home.testimonials_title': 'Ce que disent nos clients',
    'home.testimonial_1_text': 'Super plateforme, facile à utiliser et à un prix abordable.',
    'home.testimonial_1_role': 'Freelance',
    'home.testimonial_2_text': 'Un service client fantastique. Des réponses rapides et des solutions efficaces !',
    'home.testimonial_2_role': 'Directrice Marketing',
    'home.testimonial_3_text': 'Mes ventes ont explosé grâce à leur intégration fluide. Je recommande vivement !',
    'home.testimonial_3_role': 'Propriétaire e-commerce',
    'home.testimonial_4_text': 'J\'adore la simplicité d\'utilisation. Le rendu AR est d\'une qualité parfaite.',
    'home.testimonial_4_role': 'Designer 3D',
    'home.testimonial_5_text': 'Une solution innovante qui a transformé notre présentation produit.',
    'home.testimonial_5_role': 'Chef de Produit',
    'footer.ar_title': 'Réalité Augmentée',
    'footer.ar_desc': 'Apporter le monde numérique dans votre réalité. Explorez des possibilités infinies avec nos solutions AR.',
    'footer.links_title': 'Liens Rapides',
    'footer.follow_title': 'Suivez-nous',
    'footer.rights': '© 2026 Réalité Augmentée. Tous droits réservés.',
    'chatbot.welcome': "Je suis JOJMA Assistant, votre guide pour la conversion 3D et l’AR. Quelle étape souhaitez-vous accélérer aujourd’hui ?",
    'chatbot.online': 'En ligne',
    'chatbot.typing': 'En train d\'écrire...',
    'chatbot.placeholder': 'Écrivez votre message...',
    'chatbot.powered': 'Propulsé par JOJMA AI',
    'chatbot.faq_title': 'Scénarios rapides',
    'chatbot.q1': 'Je veux préparer un modèle 3D client.',
    'chatbot.q2': 'Quel format choisir pour une présentation AR ?',
    'chatbot.q3': 'Comment envoyer un lien AR à un prospect ?',
    'chatbot.q4': 'J’ai besoin d’un support rapide sur un upload.',
    'chatbot.q5': 'Comment vérifier la qualité du rendu 3D ?',
    'chatbot.q6': 'Je cherche une solution pour un projet pro.',
    'chatbot.q7': 'Montre-moi un cas client JOJMA.',
    'chatbot.q7_response': 'JOJMA a aidé une marque à déployer un catalogue AR en moins de 48h.\n\nSouhaitez-vous que je vous guide sur un cas similaire pour votre projet ?',
    'chatbot.a1': "Pour convertir un fichier, allez sur la page 'Convertisseur', déposez votre fichier (STL, OBJ, FBX) et choisissez le format de sortie (GLB/GLTF).",
    'chatbot.a2': "Nous supportons actuellement l'importation de fichiers STL, OBJ, FBX et PNG, et l'exportation vers GLB et GLTF.",
    'chatbot.a3': "Oui, la conversion de base est gratuite. Nous proposons également des packs premium pour des fonctionnalités avancées.",
    'chatbot.a4': "Vous pouvez nous contacter via la page 'Contact' ou envoyer un email à support@jojma.com.",
    'chatbot.default_a': "Merci pour votre message. Un membre de notre équipe vous répondra dès que possible. En attendant, n'hésitez pas à consulter notre FAQ."
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.converter': 'Converter',
    'nav.packs': 'AR Packs',
    'nav.ar': 'Augmented Reality',
    'nav.ar_home': 'AR Home',
    'nav.ar_experiences': 'AR Experiences',
    'nav.contact': 'Contact',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.welcome_back': 'Welcome back!',
    'auth.login_desc': 'Log in to access your space.',
    'auth.create_account': 'Create an account',
    'auth.register_desc': 'Start your JOJMA adventure for free.',
    'auth.email': 'Professional Email',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.remember': 'Remember me',
    'auth.forgot': 'Forgot?',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.register_free': 'Register for free',
    'auth.terms_agree': 'I accept the Terms of Use and Privacy Policy.',
    'home.hero_title': 'Transform Your 3D Models into Immersive AR Experiences',
    'home.hero_desc': 'JOJMA is the leading platform to convert, manage and deploy your 3D assets in augmented reality. Simple, fast and professional.',
    'home.hero_cta': 'Get Started for Free',
    'home.hero_demo': 'Watch Demo',
    'home.stats_users': 'Active Users',
    'home.stats_models': 'Converted Models',
    'home.stats_countries': 'Countries Served',
    'about.title': 'About JOJMA',
    'about.subtitle': 'Innovating in the world of Augmented Reality',
    'about.mission': 'Our Mission',
    'about.mission_text': 'Democratize access to augmented reality by providing powerful and intuitive tools for creators and businesses worldwide.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Any questions? Our team is here to help.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'home.domain_tableau': 'Painting',
    'home.domain_sculpture': 'Sculpture',
    'home.domain_moderne': 'Modern Art',
    'home.domain_abstraite': 'Abstract Art',
    'home.stats_title': '#1 AR Platform',
    'home.stats_desc': 'We are experts in augmented reality for all types of objects.',
    'home.services_title': 'Our Services',
    'home.services_subtitle': 'Discover our different offers adapted to your needs in 3D and augmented reality.',
    'home.service_free_title': 'Free 3D Converter',
    'home.service_pro_title': '3D Modeling & Augmented Reality',
    'home.service_custom_title': 'Custom AR Solution',
    'home.choose_plan': 'Choose this Plan',
    'home.recommended': 'Recommended',
    'home.service_free_features': '3D file upload: STL, OBJ, FBX, JPG, PNG|Automatic conversion to GLB, GLTF|File optimization for Augmented Reality|Download converted file (GLB, GLTF)|Online 3D preview generation|Mobile & PC compatible',
    'home.service_pro_features': 'Consultation with our 3D experts|File upload: images, plans, technical drawings|Custom 3D model creation|Conversion to compatible formats: GLB, GLTF|Unique AR Link generation for each product|Mobile & Tablet compatible|Easy AR product sharing|QR Code generation for models|File optimization for better performance|E-commerce integration (Shopify, WooCommerce...)',
    'home.service_custom_features': 'GLB 3D Product Upload|Augmented Reality Visualization|AR Link & QR Code Generation|Mobile & PC Compatible|Shopify, WooCommerce Integration|Background & Lighting Customization|Multi-Product Mode|Security & Anti-theft Protection',
    'home.domain_title': 'Augmented Reality Domain',
    'home.platform_title': 'Our Augmented Reality Platform',
    'home.platform_subtitle': 'We offer a complete platform to visualize, convert and share your 3D models in augmented reality. Discover our services that revolutionize the way you interact with your objects.',
    'home.feature_viz_title': '3D Visualization',
    'home.feature_viz_desc': 'Visualize your 3D models in augmented reality directly from your browser or mobile device.',
    'home.feature_conv_title': 'Model Conversion',
    'home.feature_conv_desc': 'Convert your models between different formats (GLTF, OBJ, FBX, STL) with exceptional quality.',
    'home.feature_share_title': 'Easy Sharing',
    'home.feature_share_desc': 'Share your AR models with your clients, colleagues or friends via a simple link or QR code.',
    'home.platform_detail_title': 'Complete and powerful AR platform',
    'home.platform_detail_features': 'Easily upload your files in GLB, GLTF, and USDZ formats to instantly convert them into interactive AR models|Visualize your products in AR directly in your personal space and test the user experience before sharing it|Easily integrate your AR models on your website or CMS with a simple code that you can copy and paste',
    'home.try_now': 'Try now',
    'home.dashboard_badge': 'Easy to use dashboard',
    'home.dashboard_title': 'See everything. Control everything.',
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.conversions': 'Conversions',
    'dashboard.ar': 'Augmented Reality',
    'dashboard.profile': 'Profile',
    'dashboard.settings': 'Settings',
    'dashboard.home': 'Home',
    'dashboard.logout': 'Logout',
    'admin.title': 'JOJMA Administration',
    'admin.overview': 'Overview',
    'admin.users': 'Users',
    'admin.models': '3D Models',
    'admin.support': 'Support',
    'admin.logs': 'Activity Logs',
    'admin.errors': 'System Errors',
    'admin.client_area': 'Client Area',
    'admin.admin': 'Admin',
    'admin.settings': 'Settings',
    'home.dashboard_desc1': 'Keep an eye on what matters to you with our easy-to-use dashboard.',
    'home.dashboard_desc2': 'Designed for both beginners and professionals, this dashboard allows you to see your platform\'s performance, perform conversions and much more in an instant.',
    'home.dashboard_features': 'Conversion between 10 popular formats|Simple and intuitive interface|Fast conversion process',
    'home.explore_features': 'Explore features',
    'home.support_title': 'Support available 24/7',
    'home.support_features': 'Chat live or email our expert team whenever you need|Our specialists accompany you in creating your custom 3D files (GLB, GLTF)|Minimal wait time: our responsive support team usually answers in less than 2 minutes|We generate ready-to-use integration code for your platform or CMS',
    'home.contact_support': 'Contact support',
    'home.online': 'Online',
    'home.chat_user_msg': 'Hello, I want to create a 3D model of my product for my e-commerce site.',
    'home.chat_support_msg1': 'Hello, I would be happy to help you. The procedure is simple and takes place in three steps. Let me show you how.',
    'home.chat_support_steps': 'Send us photos or your product mockup|We will create the GLB/GLTF file for you|We will provide you with the integration code for your site',
    'home.dashboard_formats_title': 'Formats supported by our platform',
    'home.dashboard_supported_ext': 'Supported extensions',
    'home.dashboard_used': 'Used:',
    'home.mission_title': 'At JOJMA Group, our mission is to democratize augmented reality for everyone. We have developed a complete platform to convert, visualize and share 3D models with ease.',
    'home.mission_desc': 'Our team of passionate experts works continuously to improve our technology to offer the best possible experience. Whether you are an artist, a company or an individual, our platform allows you to bring your creations to life in the real world through augmented reality.',
    'home.founder_role': 'Founder & CEO, JOJMA Group',
    'home.read_full_story': 'Read full story',
    'home.cta_title': 'Transform your 3D models and visualize them in augmented reality',
    'home.cta_desc': 'Try our free AR conversion and visualization platform with over 10 supported formats.',
    'home.get_started': 'Get started',
    'home.final_support_title': '24/7 Support, We are always available.',
    'home.final_support_desc': 'Contact us anytime, we are here to help you.',
    'home.support_phone_label': 'Call us',
    'home.support_phone_info': '+212 660 339 034',
    'home.support_chat_label': 'Chat with us',
    'home.support_chat_info': 'Live chat',
    'home.support_insta_label': 'Follow us on Instagram',
    'home.support_insta_info': 'Visit our page',
    'home.support_faq_label': 'Find answers',
    'home.support_faq_info': 'Knowledge base',
    'home.support_blog_label': 'Discover our articles',
    'home.support_blog_info': 'AR Blog',
    'home.faq_title': 'Questions? We have the Answers.',
    'home.faq_questions': 'How does Augmented Reality work?|Which devices are compatible?|How to integrate AR into my website?|Can I use my own 3D models?|Does AR work without a mobile app?|Which 3D file formats are supported?|How to generate a shareable AR link?|Do 3D models keep their textures in AR?',
    'home.see_more': 'See more',
    'home.testimonials_title': 'What our clients say',
    'home.testimonial_1_text': 'Great platform, easy to use and at an affordable price.',
    'home.testimonial_1_role': 'Freelance',
    'home.testimonial_2_text': 'Fantastic customer service. Fast answers and effective solutions!',
    'home.testimonial_2_role': 'Marketing Director',
    'home.testimonial_3_text': 'My sales exploded thanks to their smooth integration. Highly recommend!',
    'home.testimonial_3_role': 'E-commerce owner',
    'home.testimonial_4_text': 'I love the ease of use. The AR rendering is of perfect quality.',
    'home.testimonial_4_role': '3D Designer',
    'home.testimonial_5_text': 'An innovative solution that transformed our product presentation.',
    'home.testimonial_5_role': 'Product Manager',
    'footer.ar_title': 'Augmented Reality',
    'footer.ar_desc': 'Bringing the digital world into your reality. Explore endless possibilities with our AR solutions.',
    'footer.links_title': 'Quick Links',
    'footer.follow_title': 'Follow Us',
    'footer.rights': '© 2026 Augmented Reality. All Rights Reserved.',
    'chatbot.welcome': "I’m JOJMA Assistant, your guide for 3D conversion and AR. What would you like to move forward with today?",
    'chatbot.online': 'Online',
    'chatbot.typing': 'Typing...',
    'chatbot.placeholder': 'Write your message...',
    'chatbot.powered': 'Powered by JOJMA AI',
    'chatbot.faq_title': 'Quick scenarios',
    'chatbot.q1': 'I want to prepare a 3D model for a client.',
    'chatbot.q2': 'Which format is best for an AR demo?',
    'chatbot.q3': 'How to share an AR link with a prospect?',
    'chatbot.q4': 'I need fast help with an upload.',
    'chatbot.q5': 'How do I verify the 3D rendering quality?',
    'chatbot.q6': 'I’m looking for a solution for a business project.',
    'chatbot.q7': 'Show me a JOJMA client case.',
    'chatbot.q7_response': 'JOJMA helped a brand launch an AR product showcase in under 48h.\n\nWould you like me to guide you through a similar project for your business?',
    'chatbot.a1': "To convert a file, go to the 'Converter' page, drop your file (STL, OBJ, FBX) and choose the output format (GLB/GLTF).",
    'chatbot.a2': "We currently support importing STL, OBJ, FBX and PNG files, and exporting to GLB and GLTF.",
    'chatbot.a3': "Yes, basic conversion is free. We also offer premium packs for advanced features.",
    'chatbot.a4': "You can contact us via the 'Contact' page or send an email to support@jojma.com.",
    'chatbot.default_a': "Thank you for your message. A member of our team will get back to you as soon as possible. In the meantime, feel free to check our FAQ."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === 'undefined') {
      return 'fr';
    }

    const savedLanguage = window.localStorage.getItem('jojma_language');
    if (savedLanguage === 'fr' || savedLanguage === 'en') {
      return savedLanguage;
    }

    const browserLang = window.navigator.language.slice(0, 2).toLowerCase();
    return browserLang === 'en' ? 'en' : 'fr';
  });

  useEffect(() => {
    window.localStorage.setItem('jojma_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
